import { AVPlaybackSource } from "expo-av"

type voicePathType = [
    {
        nonStandardVoice: Array<Array<Array<AVPlaybackSource>>>,
        hasStandardVoice: Array<Array<Array<AVPlaybackSource>>>,
    },
    {
        nonStandardVoice: Array<Array<Array<AVPlaybackSource>>>,
        hasStandardVoice: Array<Array<Array<AVPlaybackSource>>>,
    },
    {
        nonStandardVoice: Array<Array<Array<AVPlaybackSource>>>,
        hasStandardVoice: Array<Array<Array<AVPlaybackSource>>>,
    },
]


export const voicePath: voicePathType = [
    {
        nonStandardVoice: [
            [
                [ require( "../assets/sounds/nurse/01_01a.m4a" ), require( "../assets/sounds/nurse/01_01b.m4a" ), require( "../assets/sounds/nurse/01_01c.m4a" )],
                [ require( "../assets/sounds/nurse/01_02a.m4a" ), require( "../assets/sounds/nurse/01_02b.m4a" ), require( "../assets/sounds/nurse/01_02c.m4a" )],
                [ require( "../assets/sounds/nurse/01_03a.m4a" ), require( "../assets/sounds/nurse/01_03b.m4a" ), require( "../assets/sounds/nurse/01_03c.m4a" )],
                [ require( "../assets/sounds/nurse/01_04a.m4a" ), require( "../assets/sounds/nurse/01_04b.m4a" ), require( "../assets/sounds/nurse/01_04c.m4a" )],
            ],
            [
                [ require( "../assets/sounds/nurse/02_01a.m4a" ), require( "../assets/sounds/nurse/02_01b.m4a" ), require( "../assets/sounds/nurse/02_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/02_02a.m4a" ), require( "../assets/sounds/nurse/02_02b.m4a" ), require( "../assets/sounds/nurse/02_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/02_03a.m4a" ), require( "../assets/sounds/nurse/02_03b.m4a" ), require( "../assets/sounds/nurse/02_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/02_04a.m4a" ), require( "../assets/sounds/nurse/02_04b.m4a" ), require( "../assets/sounds/nurse/02_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/02_05a.m4a" ), require( "../assets/sounds/nurse/02_05b.m4a" ), require( "../assets/sounds/nurse/02_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/02_06a.m4a" ), require( "../assets/sounds/nurse/02_06b.m4a" ), require( "../assets/sounds/nurse/02_06c.m4a" ) ],
                [ require( "../assets/sounds/nurse/02_07a.m4a" ), require( "../assets/sounds/nurse/02_07b.m4a" ), require( "../assets/sounds/nurse/02_07c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/03_01a.m4a" ), require( "../assets/sounds/nurse/03_01b.m4a" ), require( "../assets/sounds/nurse/03_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/03_02a.m4a" ), require( "../assets/sounds/nurse/03_02b.m4a" ), require( "../assets/sounds/nurse/03_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/03_03a.m4a" ), require( "../assets/sounds/nurse/03_03b.m4a" ), require( "../assets/sounds/nurse/03_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/03_04a.m4a" ), require( "../assets/sounds/nurse/03_04b.m4a" ), require( "../assets/sounds/nurse/03_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/03_05a.m4a" ), require( "../assets/sounds/nurse/03_05b.m4a" ), require( "../assets/sounds/nurse/03_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/03_06a.m4a" ), require( "../assets/sounds/nurse/03_06b.m4a" ), require( "../assets/sounds/nurse/03_06c.m4a" ) ]
            ],
            [
                [ require( "../assets/sounds/nurse/04_01a.m4a" ), require( "../assets/sounds/nurse/04_01b.m4a" ), require( "../assets/sounds/nurse/04_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/04_02a.m4a" ), require( "../assets/sounds/nurse/04_02b.m4a" ), require( "../assets/sounds/nurse/04_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/04_03a.m4a" ), require( "../assets/sounds/nurse/04_03b.m4a" ), require( "../assets/sounds/nurse/04_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/04_04a.m4a" ), require( "../assets/sounds/nurse/04_04b.m4a" ), require( "../assets/sounds/nurse/04_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/04_05a.m4a" ), require( "../assets/sounds/nurse/04_05b.m4a" ), require( "../assets/sounds/nurse/04_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/04_06a.m4a" ), require( "../assets/sounds/nurse/04_06b.m4a" ), require( "../assets/sounds/nurse/04_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/05_01a.m4a" ), require( "../assets/sounds/nurse/05_01b.m4a" ), require( "../assets/sounds/nurse/05_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/05_02a.m4a" ), require( "../assets/sounds/nurse/05_02b.m4a" ), require( "../assets/sounds/nurse/05_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/05_03a.m4a" ), require( "../assets/sounds/nurse/05_03b.m4a" ), require( "../assets/sounds/nurse/05_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/05_04a.m4a" ), require( "../assets/sounds/nurse/05_04b.m4a" ), require( "../assets/sounds/nurse/05_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/05_05a.m4a" ), require( "../assets/sounds/nurse/05_05b.m4a" ), require( "../assets/sounds/nurse/05_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/06_01a.m4a" ), require( "../assets/sounds/nurse/06_01b.m4a" ), require( "../assets/sounds/nurse/06_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/06_02a.m4a" ), require( "../assets/sounds/nurse/06_02b.m4a" ), require( "../assets/sounds/nurse/06_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/06_03a.m4a" ), require( "../assets/sounds/nurse/06_03b.m4a" ), require( "../assets/sounds/nurse/06_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/06_04a.m4a" ), require( "../assets/sounds/nurse/06_04b.m4a" ), require( "../assets/sounds/nurse/06_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/06_05a.m4a" ), require( "../assets/sounds/nurse/06_05b.m4a" ), require( "../assets/sounds/nurse/06_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/07_01a.m4a" ), require( "../assets/sounds/nurse/07_01b.m4a" ), require( "../assets/sounds/nurse/07_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/07_02a.m4a" ), require( "../assets/sounds/nurse/07_02b.m4a" ), require( "../assets/sounds/nurse/07_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/07_03a.m4a" ), require( "../assets/sounds/nurse/07_03b.m4a" ), require( "../assets/sounds/nurse/07_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/07_04a.m4a" ), require( "../assets/sounds/nurse/07_04b.m4a" ), require( "../assets/sounds/nurse/07_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/07_05a.m4a" ), require( "../assets/sounds/nurse/07_05b.m4a" ), require( "../assets/sounds/nurse/07_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/07_06a.m4a" ), require( "../assets/sounds/nurse/07_06b.m4a" ), require( "../assets/sounds/nurse/07_06c.m4a" ) ],
                [ require( "../assets/sounds/nurse/07_07a.m4a" ), require( "../assets/sounds/nurse/07_07b.m4a" ), require( "../assets/sounds/nurse/07_07c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/08_01a.m4a" ), require( "../assets/sounds/nurse/08_01b.m4a" ), require( "../assets/sounds/nurse/08_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/08_02a.m4a" ), require( "../assets/sounds/nurse/08_02b.m4a" ), require( "../assets/sounds/nurse/08_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/08_03a.m4a" ), require( "../assets/sounds/nurse/08_03b.m4a" ), require( "../assets/sounds/nurse/08_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/08_04a.m4a" ), require( "../assets/sounds/nurse/08_04b.m4a" ), require( "../assets/sounds/nurse/08_04c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/09_01a.m4a" ), require( "../assets/sounds/nurse/09_01b.m4a" ), require( "../assets/sounds/nurse/09_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/09_02a.m4a" ), require( "../assets/sounds/nurse/09_02b.m4a" ), require( "../assets/sounds/nurse/09_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/09_03a.m4a" ), require( "../assets/sounds/nurse/09_03b.m4a" ), require( "../assets/sounds/nurse/09_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/09_04a.m4a" ), require( "../assets/sounds/nurse/09_04b.m4a" ), require( "../assets/sounds/nurse/09_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/09_05a.m4a" ), require( "../assets/sounds/nurse/09_05b.m4a" ), require( "../assets/sounds/nurse/09_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/10_01a.m4a" ), require( "../assets/sounds/nurse/10_01b.m4a" ), require( "../assets/sounds/nurse/10_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/10_02a.m4a" ), require( "../assets/sounds/nurse/10_02b.m4a" ), require( "../assets/sounds/nurse/10_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/10_03a.m4a" ), require( "../assets/sounds/nurse/10_03b.m4a" ), require( "../assets/sounds/nurse/10_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/10_04a.m4a" ), require( "../assets/sounds/nurse/10_04b.m4a" ), require( "../assets/sounds/nurse/10_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/10_05a.m4a" ), require( "../assets/sounds/nurse/10_05b.m4a" ), require( "../assets/sounds/nurse/10_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/10_06a.m4a" ), require( "../assets/sounds/nurse/10_06b.m4a" ), require( "../assets/sounds/nurse/10_06c.m4a" ) ],
                [ require( "../assets/sounds/nurse/10_07a.m4a" ), require( "../assets/sounds/nurse/10_07b.m4a" ), require( "../assets/sounds/nurse/10_07c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/11_01a.m4a" ), require( "../assets/sounds/nurse/11_01b.m4a" ), require( "../assets/sounds/nurse/11_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/11_02a.m4a" ), require( "../assets/sounds/nurse/11_02b.m4a" ), require( "../assets/sounds/nurse/11_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/11_03a.m4a" ), require( "../assets/sounds/nurse/11_03b.m4a" ), require( "../assets/sounds/nurse/11_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/11_04a.m4a" ), require( "../assets/sounds/nurse/11_04b.m4a" ), require( "../assets/sounds/nurse/11_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/11_05a.m4a" ), require( "../assets/sounds/nurse/11_05b.m4a" ), require( "../assets/sounds/nurse/11_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/11_06a.m4a" ), require( "../assets/sounds/nurse/11_06b.m4a" ), require( "../assets/sounds/nurse/11_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/12_01a.m4a" ), require( "../assets/sounds/nurse/12_01b.m4a" ), require( "../assets/sounds/nurse/12_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/12_02a.m4a" ), require( "../assets/sounds/nurse/12_02b.m4a" ), require( "../assets/sounds/nurse/12_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/12_03a.m4a" ), require( "../assets/sounds/nurse/12_03b.m4a" ), require( "../assets/sounds/nurse/12_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/12_04a.m4a" ), require( "../assets/sounds/nurse/12_04b.m4a" ), require( "../assets/sounds/nurse/12_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/12_05a.m4a" ), require( "../assets/sounds/nurse/12_05b.m4a" ), require( "../assets/sounds/nurse/12_05c.m4a" ) ],
                [ require( "../assets/sounds/nurse/12_06a.m4a" ), require( "../assets/sounds/nurse/12_06b.m4a" ), require( "../assets/sounds/nurse/12_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/13_01a.m4a" ), require( "../assets/sounds/nurse/13_01b.m4a" ), require( "../assets/sounds/nurse/13_01c.m4a" ) ],
                [ require( "../assets/sounds/nurse/13_02a.m4a" ), require( "../assets/sounds/nurse/13_02b.m4a" ), require( "../assets/sounds/nurse/13_02c.m4a" ) ],
                [ require( "../assets/sounds/nurse/13_03a.m4a" ), require( "../assets/sounds/nurse/13_03b.m4a" ), require( "../assets/sounds/nurse/13_03c.m4a" ) ],
                [ require( "../assets/sounds/nurse/13_04a.m4a" ), require( "../assets/sounds/nurse/13_04b.m4a" ), require( "../assets/sounds/nurse/13_04c.m4a" ) ],
                [ require( "../assets/sounds/nurse/13_05a.m4a" ), require( "../assets/sounds/nurse/13_05b.m4a" ), require( "../assets/sounds/nurse/13_05c.m4a" ) ],
            ]
        ]
        ,
        hasStandardVoice: [
            [
                [ require( "../assets/sounds/nurse/14_01a.m4a" ), require( "../assets/sounds/nurse/14_01b.m4a" ), require( "../assets/sounds/nurse/14_01c.m4a" ), require( "../assets/sounds/nurse/14_01b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_02a.m4a" ), require( "../assets/sounds/nurse/14_02b.m4a" ), require( "../assets/sounds/nurse/14_02c.m4a" ), require( "../assets/sounds/nurse/14_02b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_03a.m4a" ), require( "../assets/sounds/nurse/14_03b.m4a" ), require( "../assets/sounds/nurse/14_03c.m4a" ), require( "../assets/sounds/nurse/14_03b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_04a.m4a" ), require( "../assets/sounds/nurse/14_04b.m4a" ), require( "../assets/sounds/nurse/14_04c.m4a" ), require( "../assets/sounds/nurse/14_04b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_05a.m4a" ), require( "../assets/sounds/nurse/14_05b.m4a" ), require( "../assets/sounds/nurse/14_05c.m4a" ), require( "../assets/sounds/nurse/14_05b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_06a.m4a" ), require( "../assets/sounds/nurse/14_06b.m4a" ), require( "../assets/sounds/nurse/14_06c.m4a" ), require( "../assets/sounds/nurse/14_06b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_07a.m4a" ), require( "../assets/sounds/nurse/14_07b.m4a" ), require( "../assets/sounds/nurse/14_07c.m4a" ), require( "../assets/sounds/nurse/14_07b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_08a.m4a" ), require( "../assets/sounds/nurse/14_08b.m4a" ), require( "../assets/sounds/nurse/14_08c.m4a" ), require( "../assets/sounds/nurse/14_08b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_09a.m4a" ), require( "../assets/sounds/nurse/14_09b.m4a" ), require( "../assets/sounds/nurse/14_09c.m4a" ), require( "../assets/sounds/nurse/14_09b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_10a.m4a" ), require( "../assets/sounds/nurse/14_10b.m4a" ), require( "../assets/sounds/nurse/14_10c.m4a" ), require( "../assets/sounds/nurse/14_10b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/14_11a.m4a" ), require( "../assets/sounds/nurse/14_11b.m4a" ), require( "../assets/sounds/nurse/14_11c.m4a" ), require( "../assets/sounds/nurse/14_11b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/15_01a.m4a" ), require( "../assets/sounds/nurse/15_01b.m4a" ), require( "../assets/sounds/nurse/15_01c.m4a" ), require( "../assets/sounds/nurse/15_01b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_02a.m4a" ), require( "../assets/sounds/nurse/15_02b.m4a" ), require( "../assets/sounds/nurse/15_02c.m4a" ), require( "../assets/sounds/nurse/15_02b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_03a.m4a" ), require( "../assets/sounds/nurse/15_03b.m4a" ), require( "../assets/sounds/nurse/15_03c.m4a" ), require( "../assets/sounds/nurse/15_03b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_04a.m4a" ), require( "../assets/sounds/nurse/15_04b.m4a" ), require( "../assets/sounds/nurse/15_04c.m4a" ), require( "../assets/sounds/nurse/15_04b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_05a.m4a" ), require( "../assets/sounds/nurse/15_05b.m4a" ), require( "../assets/sounds/nurse/15_05c.m4a" ), require( "../assets/sounds/nurse/15_05b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_06a.m4a" ), require( "../assets/sounds/nurse/15_06b.m4a" ), require( "../assets/sounds/nurse/15_06c.m4a" ), require( "../assets/sounds/nurse/15_06b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_07a.m4a" ), require( "../assets/sounds/nurse/15_07b.m4a" ), require( "../assets/sounds/nurse/15_07c.m4a" ), require( "../assets/sounds/nurse/15_07b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_08a.m4a" ), require( "../assets/sounds/nurse/15_08b.m4a" ), require( "../assets/sounds/nurse/15_08c.m4a" ), require( "../assets/sounds/nurse/15_08b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_09a.m4a" ), require( "../assets/sounds/nurse/15_09b.m4a" ), require( "../assets/sounds/nurse/15_09c.m4a" ), require( "../assets/sounds/nurse/15_09b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_10a.m4a" ), require( "../assets/sounds/nurse/15_10b.m4a" ), require( "../assets/sounds/nurse/15_10c.m4a" ), require( "../assets/sounds/nurse/15_10b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/15_11a.m4a" ), require( "../assets/sounds/nurse/15_11b.m4a" ), require( "../assets/sounds/nurse/15_11c.m4a" ), require( "../assets/sounds/nurse/15_11b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/nurse/16_01a.m4a" ), require( "../assets/sounds/nurse/16_01b.m4a" ), require( "../assets/sounds/nurse/16_01c.m4a" ), require( "../assets/sounds/nurse/16_01b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_02a.m4a" ), require( "../assets/sounds/nurse/16_02b.m4a" ), require( "../assets/sounds/nurse/16_02c.m4a" ), require( "../assets/sounds/nurse/16_02b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_03a.m4a" ), require( "../assets/sounds/nurse/16_03b.m4a" ), require( "../assets/sounds/nurse/16_03c.m4a" ), require( "../assets/sounds/nurse/16_03b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_04a.m4a" ), require( "../assets/sounds/nurse/16_04b.m4a" ), require( "../assets/sounds/nurse/16_04c.m4a" ), require( "../assets/sounds/nurse/16_04b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_05a.m4a" ), require( "../assets/sounds/nurse/16_05b.m4a" ), require( "../assets/sounds/nurse/16_05c.m4a" ), require( "../assets/sounds/nurse/16_05b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_06a.m4a" ), require( "../assets/sounds/nurse/16_06b.m4a" ), require( "../assets/sounds/nurse/16_06c.m4a" ), require( "../assets/sounds/nurse/16_06b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_07a.m4a" ), require( "../assets/sounds/nurse/16_07b.m4a" ), require( "../assets/sounds/nurse/16_07c.m4a" ), require( "../assets/sounds/nurse/16_07b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_08a.m4a" ), require( "../assets/sounds/nurse/16_08b.m4a" ), require( "../assets/sounds/nurse/16_08c.m4a" ), require( "../assets/sounds/nurse/16_08b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_09a.m4a" ), require( "../assets/sounds/nurse/16_09b.m4a" ), require( "../assets/sounds/nurse/16_09c.m4a" ), require( "../assets/sounds/nurse/16_09b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_10a.m4a" ), require( "../assets/sounds/nurse/16_10b.m4a" ), require( "../assets/sounds/nurse/16_10c.m4a" ), require( "../assets/sounds/nurse/16_10b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_11a.m4a" ), require( "../assets/sounds/nurse/16_11b.m4a" ), require( "../assets/sounds/nurse/16_11c.m4a" ), require( "../assets/sounds/nurse/16_11b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_12a.m4a" ), require( "../assets/sounds/nurse/16_12b.m4a" ), require( "../assets/sounds/nurse/16_12c.m4a" ), require( "../assets/sounds/nurse/16_12b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_13a.m4a" ), require( "../assets/sounds/nurse/16_13b.m4a" ), require( "../assets/sounds/nurse/16_13c.m4a" ), require( "../assets/sounds/nurse/16_13b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_14a.m4a" ), require( "../assets/sounds/nurse/16_14b.m4a" ), require( "../assets/sounds/nurse/16_14c.m4a" ), require( "../assets/sounds/nurse/16_14b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_15a.m4a" ), require( "../assets/sounds/nurse/16_15b.m4a" ), require( "../assets/sounds/nurse/16_15c.m4a" ), require( "../assets/sounds/nurse/16_15b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_16a.m4a" ), require( "../assets/sounds/nurse/16_16b.m4a" ), require( "../assets/sounds/nurse/16_16c.m4a" ), require( "../assets/sounds/nurse/16_16b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_17a.m4a" ), require( "../assets/sounds/nurse/16_17b.m4a" ), require( "../assets/sounds/nurse/16_17c.m4a" ), require( "../assets/sounds/nurse/16_17b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_18a.m4a" ), require( "../assets/sounds/nurse/16_18b.m4a" ), require( "../assets/sounds/nurse/16_18c.m4a" ), require( "../assets/sounds/nurse/16_18b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_19a.m4a" ), require( "../assets/sounds/nurse/16_19b.m4a" ), require( "../assets/sounds/nurse/16_19c.m4a" ), require( "../assets/sounds/nurse/16_19b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_20a.m4a" ), require( "../assets/sounds/nurse/16_20b.m4a" ), require( "../assets/sounds/nurse/16_20c.m4a" ), require( "../assets/sounds/nurse/16_20b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_21a.m4a" ), require( "../assets/sounds/nurse/16_21b.m4a" ), require( "../assets/sounds/nurse/16_21c.m4a" ), require( "../assets/sounds/nurse/16_21b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_22a.m4a" ), require( "../assets/sounds/nurse/16_22b.m4a" ), require( "../assets/sounds/nurse/16_22c.m4a" ), require( "../assets/sounds/nurse/16_22b2.m4a" ) ],
                [ require( "../assets/sounds/nurse/16_23a.m4a" ), require( "../assets/sounds/nurse/16_23b.m4a" ), require( "../assets/sounds/nurse/16_23c.m4a" ), require( "../assets/sounds/nurse/16_23b2.m4a" ) ],
            ],
        ]
    },
    {
        nonStandardVoice: [
            [
                [ require( "../assets/sounds/meal/01_01a.m4a" ), require( "../assets/sounds/meal/01_01b.m4a" ), require( "../assets/sounds/meal/01_01c.m4a" )],
                [ require( "../assets/sounds/meal/01_02a.m4a" ), require( "../assets/sounds/meal/01_02b.m4a" ), require( "../assets/sounds/meal/01_02c.m4a" )],
                [ require( "../assets/sounds/meal/01_03a.m4a" ), require( "../assets/sounds/meal/01_03b.m4a" ), require( "../assets/sounds/meal/01_03c.m4a" )],
                [ require( "../assets/sounds/meal/01_04a.m4a" ), require( "../assets/sounds/meal/01_04b.m4a" ), require( "../assets/sounds/meal/01_04c.m4a" )],
                [ require( "../assets/sounds/meal/01_05a.m4a" ), require( "../assets/sounds/meal/01_05b.m4a" ), require( "../assets/sounds/meal/01_05c.m4a" )],
            ],
            [
                [ require( "../assets/sounds/meal/02_01a.m4a" ), require( "../assets/sounds/meal/02_01b.m4a" ), require( "../assets/sounds/meal/02_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/02_02a.m4a" ), require( "../assets/sounds/meal/02_02b.m4a" ), require( "../assets/sounds/meal/02_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/02_03a.m4a" ), require( "../assets/sounds/meal/02_03b.m4a" ), require( "../assets/sounds/meal/02_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/02_04a.m4a" ), require( "../assets/sounds/meal/02_04b.m4a" ), require( "../assets/sounds/meal/02_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/02_05a.m4a" ), require( "../assets/sounds/meal/02_05b.m4a" ), require( "../assets/sounds/meal/02_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/03_01a.m4a" ), require( "../assets/sounds/meal/03_01b.m4a" ), require( "../assets/sounds/meal/03_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_02a.m4a" ), require( "../assets/sounds/meal/03_02b.m4a" ), require( "../assets/sounds/meal/03_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_03a.m4a" ), require( "../assets/sounds/meal/03_03b.m4a" ), require( "../assets/sounds/meal/03_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_04a.m4a" ), require( "../assets/sounds/meal/03_04b.m4a" ), require( "../assets/sounds/meal/03_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_05a.m4a" ), require( "../assets/sounds/meal/03_05b.m4a" ), require( "../assets/sounds/meal/03_05c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_06a.m4a" ), require( "../assets/sounds/meal/03_06b.m4a" ), require( "../assets/sounds/meal/03_06c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_07a.m4a" ), require( "../assets/sounds/meal/03_07b.m4a" ), require( "../assets/sounds/meal/03_07c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_08a.m4a" ), require( "../assets/sounds/meal/03_08b.m4a" ), require( "../assets/sounds/meal/03_08c.m4a" ) ],
                [ require( "../assets/sounds/meal/03_09a.m4a" ), require( "../assets/sounds/meal/03_09b.m4a" ), require( "../assets/sounds/meal/03_09c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/04_01a.m4a" ), require( "../assets/sounds/meal/04_01b.m4a" ), require( "../assets/sounds/meal/04_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/04_02a.m4a" ), require( "../assets/sounds/meal/04_02b.m4a" ), require( "../assets/sounds/meal/04_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/04_03a.m4a" ), require( "../assets/sounds/meal/04_03b.m4a" ), require( "../assets/sounds/meal/04_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/04_04a.m4a" ), require( "../assets/sounds/meal/04_04b.m4a" ), require( "../assets/sounds/meal/04_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/04_05a.m4a" ), require( "../assets/sounds/meal/04_05b.m4a" ), require( "../assets/sounds/meal/04_05c.m4a" ) ],
                [ require( "../assets/sounds/meal/04_06a.m4a" ), require( "../assets/sounds/meal/04_06b.m4a" ), require( "../assets/sounds/meal/04_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/05_01a.m4a" ), require( "../assets/sounds/meal/05_01b.m4a" ), require( "../assets/sounds/meal/05_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/05_02a.m4a" ), require( "../assets/sounds/meal/05_02b.m4a" ), require( "../assets/sounds/meal/05_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/05_03a.m4a" ), require( "../assets/sounds/meal/05_03b.m4a" ), require( "../assets/sounds/meal/05_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/05_04a.m4a" ), require( "../assets/sounds/meal/05_04b.m4a" ), require( "../assets/sounds/meal/05_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/05_05a.m4a" ), require( "../assets/sounds/meal/05_05b.m4a" ), require( "../assets/sounds/meal/05_05c.m4a" ) ],
                [ require( "../assets/sounds/meal/05_06a.m4a" ), require( "../assets/sounds/meal/05_06b.m4a" ), require( "../assets/sounds/meal/05_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/06_01a.m4a" ), require( "../assets/sounds/meal/06_01b.m4a" ), require( "../assets/sounds/meal/06_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/06_02a.m4a" ), require( "../assets/sounds/meal/06_02b.m4a" ), require( "../assets/sounds/meal/06_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/06_03a.m4a" ), require( "../assets/sounds/meal/06_03b.m4a" ), require( "../assets/sounds/meal/06_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/06_04a.m4a" ), require( "../assets/sounds/meal/06_04b.m4a" ), require( "../assets/sounds/meal/06_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/06_05a.m4a" ), require( "../assets/sounds/meal/06_05b.m4a" ), require( "../assets/sounds/meal/06_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/07_01a.m4a" ), require( "../assets/sounds/meal/07_01b.m4a" ), require( "../assets/sounds/meal/07_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/07_02a.m4a" ), require( "../assets/sounds/meal/07_02b.m4a" ), require( "../assets/sounds/meal/07_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/07_03a.m4a" ), require( "../assets/sounds/meal/07_03b.m4a" ), require( "../assets/sounds/meal/07_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/07_04a.m4a" ), require( "../assets/sounds/meal/07_04b.m4a" ), require( "../assets/sounds/meal/07_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/07_05a.m4a" ), require( "../assets/sounds/meal/07_05b.m4a" ), require( "../assets/sounds/meal/07_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/08_01a.m4a" ), require( "../assets/sounds/meal/08_01b.m4a" ), require( "../assets/sounds/meal/08_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/08_02a.m4a" ), require( "../assets/sounds/meal/08_02b.m4a" ), require( "../assets/sounds/meal/08_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/08_03a.m4a" ), require( "../assets/sounds/meal/08_03b.m4a" ), require( "../assets/sounds/meal/08_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/08_04a.m4a" ), require( "../assets/sounds/meal/08_04b.m4a" ), require( "../assets/sounds/meal/08_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/08_05a.m4a" ), require( "../assets/sounds/meal/08_05b.m4a" ), require( "../assets/sounds/meal/08_05c.m4a" ) ],
                [ require( "../assets/sounds/meal/08_06a.m4a" ), require( "../assets/sounds/meal/08_06b.m4a" ), require( "../assets/sounds/meal/08_06c.m4a" ) ],

            ],
            [
                [ require( "../assets/sounds/meal/09_01a.m4a" ), require( "../assets/sounds/meal/09_01b.m4a" ), require( "../assets/sounds/meal/09_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/09_02a.m4a" ), require( "../assets/sounds/meal/09_02b.m4a" ), require( "../assets/sounds/meal/09_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/09_03a.m4a" ), require( "../assets/sounds/meal/09_03b.m4a" ), require( "../assets/sounds/meal/09_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/09_04a.m4a" ), require( "../assets/sounds/meal/09_04b.m4a" ), require( "../assets/sounds/meal/09_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/09_05a.m4a" ), require( "../assets/sounds/meal/09_05b.m4a" ), require( "../assets/sounds/meal/09_05c.m4a" ) ],
                [ require( "../assets/sounds/meal/09_06a.m4a" ), require( "../assets/sounds/meal/09_06b.m4a" ), require( "../assets/sounds/meal/09_06c.m4a" ) ],

            ],
            [
                [ require( "../assets/sounds/meal/10_01a.m4a" ), require( "../assets/sounds/meal/10_01b.m4a" ), require( "../assets/sounds/meal/10_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/10_02a.m4a" ), require( "../assets/sounds/meal/10_02b.m4a" ), require( "../assets/sounds/meal/10_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/10_03a.m4a" ), require( "../assets/sounds/meal/10_03b.m4a" ), require( "../assets/sounds/meal/10_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/10_04a.m4a" ), require( "../assets/sounds/meal/10_04b.m4a" ), require( "../assets/sounds/meal/10_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/10_05a.m4a" ), require( "../assets/sounds/meal/10_05b.m4a" ), require( "../assets/sounds/meal/10_05c.m4a" ) ],
                [ require( "../assets/sounds/meal/10_06a.m4a" ), require( "../assets/sounds/meal/10_06b.m4a" ), require( "../assets/sounds/meal/10_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/11_01a.m4a" ), require( "../assets/sounds/meal/11_01b.m4a" ), require( "../assets/sounds/meal/11_01c.m4a" ) ],
                [ require( "../assets/sounds/meal/11_02a.m4a" ), require( "../assets/sounds/meal/11_02b.m4a" ), require( "../assets/sounds/meal/11_02c.m4a" ) ],
                [ require( "../assets/sounds/meal/11_03a.m4a" ), require( "../assets/sounds/meal/11_03b.m4a" ), require( "../assets/sounds/meal/11_03c.m4a" ) ],
                [ require( "../assets/sounds/meal/11_04a.m4a" ), require( "../assets/sounds/meal/11_04b.m4a" ), require( "../assets/sounds/meal/11_04c.m4a" ) ],
                [ require( "../assets/sounds/meal/11_05a.m4a" ), require( "../assets/sounds/meal/11_05b.m4a" ), require( "../assets/sounds/meal/11_05c.m4a" ) ],
            ],
        ],

        hasStandardVoice: [
            [
                [ require( "../assets/sounds/meal/12_01a.m4a" ), require( "../assets/sounds/meal/12_01b.m4a" ), require( "../assets/sounds/meal/12_01c.m4a" ), require( "../assets/sounds/meal/12_01b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_02a.m4a" ), require( "../assets/sounds/meal/12_02b.m4a" ), require( "../assets/sounds/meal/12_02c.m4a" ), require( "../assets/sounds/meal/12_02b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_03a.m4a" ), require( "../assets/sounds/meal/12_03b.m4a" ), require( "../assets/sounds/meal/12_03c.m4a" ), require( "../assets/sounds/meal/12_03b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_04a.m4a" ), require( "../assets/sounds/meal/12_04b.m4a" ), require( "../assets/sounds/meal/12_04c.m4a" ), require( "../assets/sounds/meal/12_04b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_05a.m4a" ), require( "../assets/sounds/meal/12_05b.m4a" ), require( "../assets/sounds/meal/12_05c.m4a" ), require( "../assets/sounds/meal/12_05b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_06a.m4a" ), require( "../assets/sounds/meal/12_06b.m4a" ), require( "../assets/sounds/meal/12_06c.m4a" ), require( "../assets/sounds/meal/12_06b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_07a.m4a" ), require( "../assets/sounds/meal/12_07b.m4a" ), require( "../assets/sounds/meal/12_07c.m4a" ), require( "../assets/sounds/meal/12_07b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_08a.m4a" ), require( "../assets/sounds/meal/12_08b.m4a" ), require( "../assets/sounds/meal/12_08c.m4a" ), require( "../assets/sounds/meal/12_08b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_09a.m4a" ), require( "../assets/sounds/meal/12_09b.m4a" ), require( "../assets/sounds/meal/12_09c.m4a" ), require( "../assets/sounds/meal/12_09b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_10a.m4a" ), require( "../assets/sounds/meal/12_10b.m4a" ), require( "../assets/sounds/meal/12_10c.m4a" ), require( "../assets/sounds/meal/12_10b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_11a.m4a" ), require( "../assets/sounds/meal/12_11b.m4a" ), require( "../assets/sounds/meal/12_11c.m4a" ), require( "../assets/sounds/meal/12_11b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_12a.m4a" ), require( "../assets/sounds/meal/12_12b.m4a" ), require( "../assets/sounds/meal/12_12c.m4a" ), require( "../assets/sounds/meal/12_12b2.m4a" ) ],
                [ require( "../assets/sounds/meal/12_13a.m4a" ), require( "../assets/sounds/meal/12_13b.m4a" ), require( "../assets/sounds/meal/12_13c.m4a" ), require( "../assets/sounds/meal/12_13b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/13_01a.m4a" ), require( "../assets/sounds/meal/13_01b.m4a" ), require( "../assets/sounds/meal/13_01c.m4a" ), require( "../assets/sounds/meal/13_01b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_02a.m4a" ), require( "../assets/sounds/meal/13_02b.m4a" ), require( "../assets/sounds/meal/13_02c.m4a" ), require( "../assets/sounds/meal/13_02b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_03a.m4a" ), require( "../assets/sounds/meal/13_03b.m4a" ), require( "../assets/sounds/meal/13_03c.m4a" ), require( "../assets/sounds/meal/13_03b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_04a.m4a" ), require( "../assets/sounds/meal/13_04b.m4a" ), require( "../assets/sounds/meal/13_04c.m4a" ), require( "../assets/sounds/meal/13_04b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_05a.m4a" ), require( "../assets/sounds/meal/13_05b.m4a" ), require( "../assets/sounds/meal/13_05c.m4a" ), require( "../assets/sounds/meal/13_05b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_06a.m4a" ), require( "../assets/sounds/meal/13_06b.m4a" ), require( "../assets/sounds/meal/13_06c.m4a" ), require( "../assets/sounds/meal/13_06b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_07a.m4a" ), require( "../assets/sounds/meal/13_07b.m4a" ), require( "../assets/sounds/meal/13_07c.m4a" ), require( "../assets/sounds/meal/13_07b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_08a.m4a" ), require( "../assets/sounds/meal/13_08b.m4a" ), require( "../assets/sounds/meal/13_08c.m4a" ), require( "../assets/sounds/meal/13_08b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_09a.m4a" ), require( "../assets/sounds/meal/13_09b.m4a" ), require( "../assets/sounds/meal/13_09c.m4a" ), require( "../assets/sounds/meal/13_09b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_10a.m4a" ), require( "../assets/sounds/meal/13_10b.m4a" ), require( "../assets/sounds/meal/13_10c.m4a" ), require( "../assets/sounds/meal/13_10b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_11a.m4a" ), require( "../assets/sounds/meal/13_11b.m4a" ), require( "../assets/sounds/meal/13_11c.m4a" ), require( "../assets/sounds/meal/13_11b2.m4a" ) ],
                [ require( "../assets/sounds/meal/13_12a.m4a" ), require( "../assets/sounds/meal/13_12b.m4a" ), require( "../assets/sounds/meal/13_12c.m4a" ), require( "../assets/sounds/meal/13_12b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/meal/14_01a.m4a" ), require( "../assets/sounds/meal/14_01b.m4a" ), require( "../assets/sounds/meal/14_01c.m4a" ), require( "../assets/sounds/meal/14_01b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_02a.m4a" ), require( "../assets/sounds/meal/14_02b.m4a" ), require( "../assets/sounds/meal/14_02c.m4a" ), require( "../assets/sounds/meal/14_02b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_03a.m4a" ), require( "../assets/sounds/meal/14_03b.m4a" ), require( "../assets/sounds/meal/14_03c.m4a" ), require( "../assets/sounds/meal/14_03b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_04a.m4a" ), require( "../assets/sounds/meal/14_04b.m4a" ), require( "../assets/sounds/meal/14_04c.m4a" ), require( "../assets/sounds/meal/14_04b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_05a.m4a" ), require( "../assets/sounds/meal/14_05b.m4a" ), require( "../assets/sounds/meal/14_05c.m4a" ), require( "../assets/sounds/meal/14_05b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_06a.m4a" ), require( "../assets/sounds/meal/14_06b.m4a" ), require( "../assets/sounds/meal/14_06c.m4a" ), require( "../assets/sounds/meal/14_06b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_07a.m4a" ), require( "../assets/sounds/meal/14_07b.m4a" ), require( "../assets/sounds/meal/14_07c.m4a" ), require( "../assets/sounds/meal/14_07b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_08a.m4a" ), require( "../assets/sounds/meal/14_08b.m4a" ), require( "../assets/sounds/meal/14_08c.m4a" ), require( "../assets/sounds/meal/14_08b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_09a.m4a" ), require( "../assets/sounds/meal/14_09b.m4a" ), require( "../assets/sounds/meal/14_09c.m4a" ), require( "../assets/sounds/meal/14_09b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_10a.m4a" ), require( "../assets/sounds/meal/14_10b.m4a" ), require( "../assets/sounds/meal/14_10c.m4a" ), require( "../assets/sounds/meal/14_10b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_11a.m4a" ), require( "../assets/sounds/meal/14_11b.m4a" ), require( "../assets/sounds/meal/14_11c.m4a" ), require( "../assets/sounds/meal/14_11b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_12a.m4a" ), require( "../assets/sounds/meal/14_12b.m4a" ), require( "../assets/sounds/meal/14_12c.m4a" ), require( "../assets/sounds/meal/14_12b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_13a.m4a" ), require( "../assets/sounds/meal/14_13b.m4a" ), require( "../assets/sounds/meal/14_13c.m4a" ), require( "../assets/sounds/meal/14_13b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_14a.m4a" ), require( "../assets/sounds/meal/14_14b.m4a" ), require( "../assets/sounds/meal/14_14c.m4a" ), require( "../assets/sounds/meal/14_14b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_15a.m4a" ), require( "../assets/sounds/meal/14_15b.m4a" ), require( "../assets/sounds/meal/14_15c.m4a" ), require( "../assets/sounds/meal/14_15b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_16a.m4a" ), require( "../assets/sounds/meal/14_16b.m4a" ), require( "../assets/sounds/meal/14_16c.m4a" ), require( "../assets/sounds/meal/14_16b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_17a.m4a" ), require( "../assets/sounds/meal/14_17b.m4a" ), require( "../assets/sounds/meal/14_17c.m4a" ), require( "../assets/sounds/meal/14_17b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_18a.m4a" ), require( "../assets/sounds/meal/14_18b.m4a" ), require( "../assets/sounds/meal/14_18c.m4a" ), require( "../assets/sounds/meal/14_18b2.m4a" ) ],
                [ require( "../assets/sounds/meal/14_19a.m4a" ), require( "../assets/sounds/meal/14_19b.m4a" ), require( "../assets/sounds/meal/14_19c.m4a" ), require( "../assets/sounds/meal/14_19b2.m4a" ) ],
            ],
        ]
    },
    {
        nonStandardVoice: [
            [
                [ require( "../assets/sounds/life/01_01a.m4a" ), require( "../assets/sounds/life/01_01b.m4a" ), require( "../assets/sounds/life/01_01c.m4a" )],
                [ require( "../assets/sounds/life/01_02a.m4a" ), require( "../assets/sounds/life/01_02b.m4a" ), require( "../assets/sounds/life/01_02c.m4a" )],
                [ require( "../assets/sounds/life/01_03a.m4a" ), require( "../assets/sounds/life/01_03b.m4a" ), require( "../assets/sounds/life/01_03c.m4a" )],
                [ require( "../assets/sounds/life/01_04a.m4a" ), require( "../assets/sounds/life/01_04b.m4a" ), require( "../assets/sounds/life/01_04c.m4a" )],
                [ require( "../assets/sounds/life/01_05a.m4a" ), require( "../assets/sounds/life/01_05b.m4a" ), require( "../assets/sounds/life/01_05c.m4a" ) ],
                [ require( "../assets/sounds/life/01_06a.m4a" ), require( "../assets/sounds/life/01_06b.m4a" ), require( "../assets/sounds/life/01_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/02_01a.m4a" ), require( "../assets/sounds/life/02_01b.m4a" ), require( "../assets/sounds/life/02_01c.m4a" ) ],
                [ require( "../assets/sounds/life/02_02a.m4a" ), require( "../assets/sounds/life/02_02b.m4a" ), require( "../assets/sounds/life/02_02c.m4a" ) ],
                [ require( "../assets/sounds/life/02_03a.m4a" ), require( "../assets/sounds/life/02_03b.m4a" ), require( "../assets/sounds/life/02_03c.m4a" ) ],
                [ require( "../assets/sounds/life/02_04a.m4a" ), require( "../assets/sounds/life/02_04b.m4a" ), require( "../assets/sounds/life/02_04c.m4a" ) ],
                [ require( "../assets/sounds/life/02_05a.m4a" ), require( "../assets/sounds/life/02_05b.m4a" ), require( "../assets/sounds/life/02_05c.m4a" ) ],
                [ require( "../assets/sounds/life/02_06a.m4a" ), require( "../assets/sounds/life/02_06b.m4a" ), require( "../assets/sounds/life/02_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/03_01a.m4a" ), require( "../assets/sounds/life/03_01b.m4a" ), require( "../assets/sounds/life/03_01c.m4a" ) ],
                [ require( "../assets/sounds/life/03_02a.m4a" ), require( "../assets/sounds/life/03_02b.m4a" ), require( "../assets/sounds/life/03_02c.m4a" ) ],
                [ require( "../assets/sounds/life/03_03a.m4a" ), require( "../assets/sounds/life/03_03b.m4a" ), require( "../assets/sounds/life/03_03c.m4a" ) ],
                [ require( "../assets/sounds/life/03_04a.m4a" ), require( "../assets/sounds/life/03_04b.m4a" ), require( "../assets/sounds/life/03_04c.m4a" ) ],
                [ require( "../assets/sounds/life/03_05a.m4a" ), require( "../assets/sounds/life/03_05b.m4a" ), require( "../assets/sounds/life/03_05c.m4a" ) ],
                [ require( "../assets/sounds/life/03_06a.m4a" ), require( "../assets/sounds/life/03_06b.m4a" ), require( "../assets/sounds/life/03_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/04_01a.m4a" ), require( "../assets/sounds/life/04_01b.m4a" ), require( "../assets/sounds/life/04_01c.m4a" ) ],
                [ require( "../assets/sounds/life/04_02a.m4a" ), require( "../assets/sounds/life/04_02b.m4a" ), require( "../assets/sounds/life/04_02c.m4a" ) ],
                [ require( "../assets/sounds/life/04_03a.m4a" ), require( "../assets/sounds/life/04_03b.m4a" ), require( "../assets/sounds/life/04_03c.m4a" ) ],
                [ require( "../assets/sounds/life/04_04a.m4a" ), require( "../assets/sounds/life/04_04b.m4a" ), require( "../assets/sounds/life/04_04c.m4a" ) ],
                [ require( "../assets/sounds/life/04_05a.m4a" ), require( "../assets/sounds/life/04_05b.m4a" ), require( "../assets/sounds/life/04_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/05_01a.m4a" ), require( "../assets/sounds/life/05_01b.m4a" ), require( "../assets/sounds/life/05_01c.m4a" ) ],
                [ require( "../assets/sounds/life/05_02a.m4a" ), require( "../assets/sounds/life/05_02b.m4a" ), require( "../assets/sounds/life/05_02c.m4a" ) ],
                [ require( "../assets/sounds/life/05_03a.m4a" ), require( "../assets/sounds/life/05_03b.m4a" ), require( "../assets/sounds/life/05_03c.m4a" ) ],
                [ require( "../assets/sounds/life/05_04a.m4a" ), require( "../assets/sounds/life/05_04b.m4a" ), require( "../assets/sounds/life/05_04c.m4a" ) ],
                [ require( "../assets/sounds/life/05_05a.m4a" ), require( "../assets/sounds/life/05_05b.m4a" ), require( "../assets/sounds/life/05_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/06_01a.m4a" ), require( "../assets/sounds/life/06_01b.m4a" ), require( "../assets/sounds/life/06_01c.m4a" ) ],
                [ require( "../assets/sounds/life/06_02a.m4a" ), require( "../assets/sounds/life/06_02b.m4a" ), require( "../assets/sounds/life/06_02c.m4a" ) ],
                [ require( "../assets/sounds/life/06_03a.m4a" ), require( "../assets/sounds/life/06_03b.m4a" ), require( "../assets/sounds/life/06_03c.m4a" ) ],
                [ require( "../assets/sounds/life/06_04a.m4a" ), require( "../assets/sounds/life/06_04b.m4a" ), require( "../assets/sounds/life/06_04c.m4a" ) ],
                [ require( "../assets/sounds/life/06_05a.m4a" ), require( "../assets/sounds/life/06_05b.m4a" ), require( "../assets/sounds/life/06_05c.m4a" ) ],
                [ require( "../assets/sounds/life/06_06a.m4a" ), require( "../assets/sounds/life/06_06b.m4a" ), require( "../assets/sounds/life/06_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/07_01a.m4a" ), require( "../assets/sounds/life/07_01b.m4a" ), require( "../assets/sounds/life/07_01c.m4a" ) ],
                [ require( "../assets/sounds/life/07_02a.m4a" ), require( "../assets/sounds/life/07_02b.m4a" ), require( "../assets/sounds/life/07_02c.m4a" ) ],
                [ require( "../assets/sounds/life/07_03a.m4a" ), require( "../assets/sounds/life/07_03b.m4a" ), require( "../assets/sounds/life/07_03c.m4a" ) ],
                [ require( "../assets/sounds/life/07_04a.m4a" ), require( "../assets/sounds/life/07_04b.m4a" ), require( "../assets/sounds/life/07_04c.m4a" ) ],
                [ require( "../assets/sounds/life/07_05a.m4a" ), require( "../assets/sounds/life/07_05b.m4a" ), require( "../assets/sounds/life/07_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/08_01a.m4a" ), require( "../assets/sounds/life/08_01b.m4a" ), require( "../assets/sounds/life/08_01c.m4a" ) ],
                [ require( "../assets/sounds/life/08_02a.m4a" ), require( "../assets/sounds/life/08_02b.m4a" ), require( "../assets/sounds/life/08_02c.m4a" ) ],
                [ require( "../assets/sounds/life/08_03a.m4a" ), require( "../assets/sounds/life/08_03b.m4a" ), require( "../assets/sounds/life/08_03c.m4a" ) ],
                [ require( "../assets/sounds/life/08_04a.m4a" ), require( "../assets/sounds/life/08_04b.m4a" ), require( "../assets/sounds/life/08_04c.m4a" ) ],
                [ require( "../assets/sounds/life/08_05a.m4a" ), require( "../assets/sounds/life/08_05b.m4a" ), require( "../assets/sounds/life/08_05c.m4a" ) ],

            ],
            [
                [ require( "../assets/sounds/life/09_01a.m4a" ), require( "../assets/sounds/life/09_01b.m4a" ), require( "../assets/sounds/life/09_01c.m4a" ) ],
                [ require( "../assets/sounds/life/09_02a.m4a" ), require( "../assets/sounds/life/09_02b.m4a" ), require( "../assets/sounds/life/09_02c.m4a" ) ],
                [ require( "../assets/sounds/life/09_03a.m4a" ), require( "../assets/sounds/life/09_03b.m4a" ), require( "../assets/sounds/life/09_03c.m4a" ) ],
                [ require( "../assets/sounds/life/09_04a.m4a" ), require( "../assets/sounds/life/09_04b.m4a" ), require( "../assets/sounds/life/09_04c.m4a" ) ],
                [ require( "../assets/sounds/life/09_05a.m4a" ), require( "../assets/sounds/life/09_05b.m4a" ), require( "../assets/sounds/life/09_05c.m4a" ) ],

            ],
            [
                [ require( "../assets/sounds/life/10_01a.m4a" ), require( "../assets/sounds/life/10_01b.m4a" ), require( "../assets/sounds/life/10_01c.m4a" ) ],
                [ require( "../assets/sounds/life/10_02a.m4a" ), require( "../assets/sounds/life/10_02b.m4a" ), require( "../assets/sounds/life/10_02c.m4a" ) ],
                [ require( "../assets/sounds/life/10_03a.m4a" ), require( "../assets/sounds/life/10_03b.m4a" ), require( "../assets/sounds/life/10_03c.m4a" ) ],
                [ require( "../assets/sounds/life/10_04a.m4a" ), require( "../assets/sounds/life/10_04b.m4a" ), require( "../assets/sounds/life/10_04c.m4a" ) ],
                [ require( "../assets/sounds/life/10_05a.m4a" ), require( "../assets/sounds/life/10_05b.m4a" ), require( "../assets/sounds/life/10_05c.m4a" ) ],
                [ require( "../assets/sounds/life/10_06a.m4a" ), require( "../assets/sounds/life/10_06b.m4a" ), require( "../assets/sounds/life/10_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/11_01a.m4a" ), require( "../assets/sounds/life/11_01b.m4a" ), require( "../assets/sounds/life/11_01c.m4a" ) ],
                [ require( "../assets/sounds/life/11_02a.m4a" ), require( "../assets/sounds/life/11_02b.m4a" ), require( "../assets/sounds/life/11_02c.m4a" ) ],
                [ require( "../assets/sounds/life/11_03a.m4a" ), require( "../assets/sounds/life/11_03b.m4a" ), require( "../assets/sounds/life/11_03c.m4a" ) ],
                [ require( "../assets/sounds/life/11_04a.m4a" ), require( "../assets/sounds/life/11_04b.m4a" ), require( "../assets/sounds/life/11_04c.m4a" ) ],
                [ require( "../assets/sounds/life/11_05a.m4a" ), require( "../assets/sounds/life/11_05b.m4a" ), require( "../assets/sounds/life/11_05c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/12_01a.m4a" ), require( "../assets/sounds/life/12_01b.m4a" ), require( "../assets/sounds/life/12_01c.m4a" ) ],
                [ require( "../assets/sounds/life/12_02a.m4a" ), require( "../assets/sounds/life/12_02b.m4a" ), require( "../assets/sounds/life/12_02c.m4a" ) ],
                [ require( "../assets/sounds/life/12_03a.m4a" ), require( "../assets/sounds/life/12_03b.m4a" ), require( "../assets/sounds/life/12_03c.m4a" ) ],
                [ require( "../assets/sounds/life/12_04a.m4a" ), require( "../assets/sounds/life/12_04b.m4a" ), require( "../assets/sounds/life/12_04c.m4a" ) ],
                [ require( "../assets/sounds/life/12_05a.m4a" ), require( "../assets/sounds/life/12_05b.m4a" ), require( "../assets/sounds/life/12_05c.m4a" ) ],
                [ require( "../assets/sounds/life/12_06a.m4a" ), require( "../assets/sounds/life/12_06b.m4a" ), require( "../assets/sounds/life/12_06c.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/13_01a.m4a" ), require( "../assets/sounds/life/13_01b.m4a" ), require( "../assets/sounds/life/13_01c.m4a" ) ],
                [ require( "../assets/sounds/life/13_02a.m4a" ), require( "../assets/sounds/life/13_02b.m4a" ), require( "../assets/sounds/life/13_02c.m4a" ) ],
                [ require( "../assets/sounds/life/13_03a.m4a" ), require( "../assets/sounds/life/13_03b.m4a" ), require( "../assets/sounds/life/13_03c.m4a" ) ],
                [ require( "../assets/sounds/life/13_04a.m4a" ), require( "../assets/sounds/life/13_04b.m4a" ), require( "../assets/sounds/life/13_04c.m4a" ) ],
                [ require( "../assets/sounds/life/13_05a.m4a" ), require( "../assets/sounds/life/13_05b.m4a" ), require( "../assets/sounds/life/13_05c.m4a" ) ],
                [ require( "../assets/sounds/life/13_06a.m4a" ), require( "../assets/sounds/life/13_06b.m4a" ), require( "../assets/sounds/life/13_06c.m4a" ) ],
            ],
        ],

        hasStandardVoice: [
            [
                [ require( "../assets/sounds/life/15_01a.m4a" ), require( "../assets/sounds/life/15_01b.m4a" ), require( "../assets/sounds/life/15_01c.m4a" ), require( "../assets/sounds/life/15_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_02a.m4a" ), require( "../assets/sounds/life/15_02b.m4a" ), require( "../assets/sounds/life/15_02c.m4a" ), require( "../assets/sounds/life/15_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_03a.m4a" ), require( "../assets/sounds/life/15_03b.m4a" ), require( "../assets/sounds/life/15_03c.m4a" ), require( "../assets/sounds/life/15_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_04a.m4a" ), require( "../assets/sounds/life/15_04b.m4a" ), require( "../assets/sounds/life/15_04c.m4a" ), require( "../assets/sounds/life/15_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_05a.m4a" ), require( "../assets/sounds/life/15_05b.m4a" ), require( "../assets/sounds/life/15_05c.m4a" ), require( "../assets/sounds/life/15_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_06a.m4a" ), require( "../assets/sounds/life/15_06b.m4a" ), require( "../assets/sounds/life/15_06c.m4a" ), require( "../assets/sounds/life/15_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_07a.m4a" ), require( "../assets/sounds/life/15_07b.m4a" ), require( "../assets/sounds/life/15_07c.m4a" ), require( "../assets/sounds/life/15_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_08a.m4a" ), require( "../assets/sounds/life/15_08b.m4a" ), require( "../assets/sounds/life/15_08c.m4a" ), require( "../assets/sounds/life/15_08b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_09a.m4a" ), require( "../assets/sounds/life/15_09b.m4a" ), require( "../assets/sounds/life/15_09c.m4a" ), require( "../assets/sounds/life/15_09b2.m4a" ) ],
                [ require( "../assets/sounds/life/15_10a.m4a" ), require( "../assets/sounds/life/15_10b.m4a" ), require( "../assets/sounds/life/15_10c.m4a" ), require( "../assets/sounds/life/15_10b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/16_01a.m4a" ), require( "../assets/sounds/life/16_01b.m4a" ), require( "../assets/sounds/life/16_01c.m4a" ), require( "../assets/sounds/life/16_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/16_02a.m4a" ), require( "../assets/sounds/life/16_02b.m4a" ), require( "../assets/sounds/life/16_02c.m4a" ), require( "../assets/sounds/life/16_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/16_03a.m4a" ), require( "../assets/sounds/life/16_03b.m4a" ), require( "../assets/sounds/life/16_03c.m4a" ), require( "../assets/sounds/life/16_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/16_04a.m4a" ), require( "../assets/sounds/life/16_04b.m4a" ), require( "../assets/sounds/life/16_04c.m4a" ), require( "../assets/sounds/life/16_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/16_05a.m4a" ), require( "../assets/sounds/life/16_05b.m4a" ), require( "../assets/sounds/life/16_05c.m4a" ), require( "../assets/sounds/life/16_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/16_06a.m4a" ), require( "../assets/sounds/life/16_06b.m4a" ), require( "../assets/sounds/life/16_06c.m4a" ), require( "../assets/sounds/life/16_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/16_07a.m4a" ), require( "../assets/sounds/life/16_07b.m4a" ), require( "../assets/sounds/life/16_07c.m4a" ), require( "../assets/sounds/life/16_07b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/17_01a.m4a" ), require( "../assets/sounds/life/17_01b.m4a" ), require( "../assets/sounds/life/17_01c.m4a" ), require( "../assets/sounds/life/17_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_02a.m4a" ), require( "../assets/sounds/life/17_02b.m4a" ), require( "../assets/sounds/life/17_02c.m4a" ), require( "../assets/sounds/life/17_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_03a.m4a" ), require( "../assets/sounds/life/17_03b.m4a" ), require( "../assets/sounds/life/17_03c.m4a" ), require( "../assets/sounds/life/17_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_04a.m4a" ), require( "../assets/sounds/life/17_04b.m4a" ), require( "../assets/sounds/life/17_04c.m4a" ), require( "../assets/sounds/life/17_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_05a.m4a" ), require( "../assets/sounds/life/17_05b.m4a" ), require( "../assets/sounds/life/17_05c.m4a" ), require( "../assets/sounds/life/17_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_06a.m4a" ), require( "../assets/sounds/life/17_06b.m4a" ), require( "../assets/sounds/life/17_06c.m4a" ), require( "../assets/sounds/life/17_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_07a.m4a" ), require( "../assets/sounds/life/17_07b.m4a" ), require( "../assets/sounds/life/17_07c.m4a" ), require( "../assets/sounds/life/17_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_08a.m4a" ), require( "../assets/sounds/life/17_08b.m4a" ), require( "../assets/sounds/life/17_08c.m4a" ), require( "../assets/sounds/life/17_08b2.m4a" ) ],
                [ require( "../assets/sounds/life/17_09a.m4a" ), require( "../assets/sounds/life/17_09b.m4a" ), require( "../assets/sounds/life/17_09c.m4a" ), require( "../assets/sounds/life/17_09b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/18_01a.m4a" ), require( "../assets/sounds/life/18_01b.m4a" ), require( "../assets/sounds/life/18_01c.m4a" ), require( "../assets/sounds/life/18_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_02a.m4a" ), require( "../assets/sounds/life/18_02b.m4a" ), require( "../assets/sounds/life/18_02c.m4a" ), require( "../assets/sounds/life/18_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_03a.m4a" ), require( "../assets/sounds/life/18_03b.m4a" ), require( "../assets/sounds/life/18_03c.m4a" ), require( "../assets/sounds/life/18_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_04a.m4a" ), require( "../assets/sounds/life/18_04b.m4a" ), require( "../assets/sounds/life/18_04c.m4a" ), require( "../assets/sounds/life/18_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_05a.m4a" ), require( "../assets/sounds/life/18_05b.m4a" ), require( "../assets/sounds/life/18_05c.m4a" ), require( "../assets/sounds/life/18_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_06a.m4a" ), require( "../assets/sounds/life/18_06b.m4a" ), require( "../assets/sounds/life/18_06c.m4a" ), require( "../assets/sounds/life/18_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_07a.m4a" ), require( "../assets/sounds/life/18_07b.m4a" ), require( "../assets/sounds/life/18_07c.m4a" ), require( "../assets/sounds/life/18_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/18_08a.m4a" ), require( "../assets/sounds/life/18_08b.m4a" ), require( "../assets/sounds/life/18_08c.m4a" ), require( "../assets/sounds/life/18_08b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/19_01a.m4a" ), require( "../assets/sounds/life/19_01b.m4a" ), require( "../assets/sounds/life/19_01c.m4a" ), require( "../assets/sounds/life/19_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_02a.m4a" ), require( "../assets/sounds/life/19_02b.m4a" ), require( "../assets/sounds/life/19_02c.m4a" ), require( "../assets/sounds/life/19_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_03a.m4a" ), require( "../assets/sounds/life/19_03b.m4a" ), require( "../assets/sounds/life/19_03c.m4a" ), require( "../assets/sounds/life/19_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_04a.m4a" ), require( "../assets/sounds/life/19_04b.m4a" ), require( "../assets/sounds/life/19_04c.m4a" ), require( "../assets/sounds/life/19_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_05a.m4a" ), require( "../assets/sounds/life/19_05b.m4a" ), require( "../assets/sounds/life/19_05c.m4a" ), require( "../assets/sounds/life/19_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_06a.m4a" ), require( "../assets/sounds/life/19_06b.m4a" ), require( "../assets/sounds/life/19_06c.m4a" ), require( "../assets/sounds/life/19_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_07a.m4a" ), require( "../assets/sounds/life/19_07b.m4a" ), require( "../assets/sounds/life/19_07c.m4a" ), require( "../assets/sounds/life/19_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_08a.m4a" ), require( "../assets/sounds/life/19_08b.m4a" ), require( "../assets/sounds/life/19_08c.m4a" ), require( "../assets/sounds/life/19_08b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_09a.m4a" ), require( "../assets/sounds/life/19_09b.m4a" ), require( "../assets/sounds/life/19_09c.m4a" ), require( "../assets/sounds/life/19_09b2.m4a" ) ],
                [ require( "../assets/sounds/life/19_10a.m4a" ), require( "../assets/sounds/life/19_10b.m4a" ), require( "../assets/sounds/life/19_10c.m4a" ), require( "../assets/sounds/life/19_10b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/20_01a.m4a" ), require( "../assets/sounds/life/20_01b.m4a" ), require( "../assets/sounds/life/20_01c.m4a" ), require( "../assets/sounds/life/20_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_02a.m4a" ), require( "../assets/sounds/life/20_02b.m4a" ), require( "../assets/sounds/life/20_02c.m4a" ), require( "../assets/sounds/life/20_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_03a.m4a" ), require( "../assets/sounds/life/20_03b.m4a" ), require( "../assets/sounds/life/20_03c.m4a" ), require( "../assets/sounds/life/20_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_04a.m4a" ), require( "../assets/sounds/life/20_04b.m4a" ), require( "../assets/sounds/life/20_04c.m4a" ), require( "../assets/sounds/life/20_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_05a.m4a" ), require( "../assets/sounds/life/20_05b.m4a" ), require( "../assets/sounds/life/20_05c.m4a" ), require( "../assets/sounds/life/20_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_06a.m4a" ), require( "../assets/sounds/life/20_06b.m4a" ), require( "../assets/sounds/life/20_06c.m4a" ), require( "../assets/sounds/life/20_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_07a.m4a" ), require( "../assets/sounds/life/20_07b.m4a" ), require( "../assets/sounds/life/20_07c.m4a" ), require( "../assets/sounds/life/20_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_08a.m4a" ), require( "../assets/sounds/life/20_08b.m4a" ), require( "../assets/sounds/life/20_08c.m4a" ), require( "../assets/sounds/life/20_08b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_09a.m4a" ), require( "../assets/sounds/life/20_09b.m4a" ), require( "../assets/sounds/life/20_09c.m4a" ), require( "../assets/sounds/life/20_09b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_10a.m4a" ), require( "../assets/sounds/life/20_10b.m4a" ), require( "../assets/sounds/life/20_10c.m4a" ), require( "../assets/sounds/life/20_10b2.m4a" ) ],
                [ require( "../assets/sounds/life/20_11a.m4a" ), require( "../assets/sounds/life/20_11b.m4a" ), require( "../assets/sounds/life/20_11c.m4a" ), require( "../assets/sounds/life/20_11b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/21_01a.m4a" ), require( "../assets/sounds/life/21_01b.m4a" ), require( "../assets/sounds/life/21_01c.m4a" ), require( "../assets/sounds/life/21_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_02a.m4a" ), require( "../assets/sounds/life/21_02b.m4a" ), require( "../assets/sounds/life/21_02c.m4a" ), require( "../assets/sounds/life/21_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_03a.m4a" ), require( "../assets/sounds/life/21_03b.m4a" ), require( "../assets/sounds/life/21_03c.m4a" ), require( "../assets/sounds/life/21_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_04a.m4a" ), require( "../assets/sounds/life/21_04b.m4a" ), require( "../assets/sounds/life/21_04c.m4a" ), require( "../assets/sounds/life/21_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_05a.m4a" ), require( "../assets/sounds/life/21_05b.m4a" ), require( "../assets/sounds/life/21_05c.m4a" ), require( "../assets/sounds/life/21_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_06a.m4a" ), require( "../assets/sounds/life/21_06b.m4a" ), require( "../assets/sounds/life/21_06c.m4a" ), require( "../assets/sounds/life/21_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_07a.m4a" ), require( "../assets/sounds/life/21_07b.m4a" ), require( "../assets/sounds/life/21_07c.m4a" ), require( "../assets/sounds/life/21_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_08a.m4a" ), require( "../assets/sounds/life/21_08b.m4a" ), require( "../assets/sounds/life/21_08c.m4a" ), require( "../assets/sounds/life/21_08b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_09a.m4a" ), require( "../assets/sounds/life/21_09b.m4a" ), require( "../assets/sounds/life/21_09c.m4a" ), require( "../assets/sounds/life/21_09b2.m4a" ) ],
                [ require( "../assets/sounds/life/21_10a.m4a" ), require( "../assets/sounds/life/21_10b.m4a" ), require( "../assets/sounds/life/21_10c.m4a" ), require( "../assets/sounds/life/21_10b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/22_01a.m4a" ), require( "../assets/sounds/life/22_01b.m4a" ), require( "../assets/sounds/life/22_01c.m4a" ), require( "../assets/sounds/life/22_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_02a.m4a" ), require( "../assets/sounds/life/22_02b.m4a" ), require( "../assets/sounds/life/22_02c.m4a" ), require( "../assets/sounds/life/22_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_03a.m4a" ), require( "../assets/sounds/life/22_03b.m4a" ), require( "../assets/sounds/life/22_03c.m4a" ), require( "../assets/sounds/life/22_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_04a.m4a" ), require( "../assets/sounds/life/22_04b.m4a" ), require( "../assets/sounds/life/22_04c.m4a" ), require( "../assets/sounds/life/22_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_05a.m4a" ), require( "../assets/sounds/life/22_05b.m4a" ), require( "../assets/sounds/life/22_05c.m4a" ), require( "../assets/sounds/life/22_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_06a.m4a" ), require( "../assets/sounds/life/22_06b.m4a" ), require( "../assets/sounds/life/22_06c.m4a" ), require( "../assets/sounds/life/22_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_07a.m4a" ), require( "../assets/sounds/life/22_07b.m4a" ), require( "../assets/sounds/life/22_07c.m4a" ), require( "../assets/sounds/life/22_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_08a.m4a" ), require( "../assets/sounds/life/22_08b.m4a" ), require( "../assets/sounds/life/22_08c.m4a" ), require( "../assets/sounds/life/22_08b2.m4a" ) ],
                [ require( "../assets/sounds/life/22_09a.m4a" ), require( "../assets/sounds/life/22_09b.m4a" ), require( "../assets/sounds/life/22_09c.m4a" ), require( "../assets/sounds/life/22_09b2.m4a" ) ],
            ],
            [
                [ require( "../assets/sounds/life/23_01a.m4a" ), require( "../assets/sounds/life/23_01b.m4a" ), require( "../assets/sounds/life/23_01c.m4a" ), require( "../assets/sounds/life/23_01b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_02a.m4a" ), require( "../assets/sounds/life/23_02b.m4a" ), require( "../assets/sounds/life/23_02c.m4a" ), require( "../assets/sounds/life/23_02b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_03a.m4a" ), require( "../assets/sounds/life/23_03b.m4a" ), require( "../assets/sounds/life/23_03c.m4a" ), require( "../assets/sounds/life/23_03b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_04a.m4a" ), require( "../assets/sounds/life/23_04b.m4a" ), require( "../assets/sounds/life/23_04c.m4a" ), require( "../assets/sounds/life/23_04b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_05a.m4a" ), require( "../assets/sounds/life/23_05b.m4a" ), require( "../assets/sounds/life/23_05c.m4a" ), require( "../assets/sounds/life/23_05b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_06a.m4a" ), require( "../assets/sounds/life/23_06b.m4a" ), require( "../assets/sounds/life/23_06c.m4a" ), require( "../assets/sounds/life/23_06b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_07a.m4a" ), require( "../assets/sounds/life/23_07b.m4a" ), require( "../assets/sounds/life/23_07c.m4a" ), require( "../assets/sounds/life/23_07b2.m4a" ) ],
                [ require( "../assets/sounds/life/23_08a.m4a" ), require( "../assets/sounds/life/23_08b.m4a" ), require( "../assets/sounds/life/23_08c.m4a" ), require( "../assets/sounds/life/23_08b2.m4a" ) ],
            ],
        ]
    }
]
